version: '2.4'

services:
  frontend:
    image: frontend:1.0.0
    ports:
      - 12345:12345
      - 12346:12346
  charserver:
    image: charserver:1.0.0
    depends_on:
      - frontend
  chatserver:
    image: chatserver:1.0.0
    depends_on:
      - frontend
  loginserver:
    image: loginserver:1.0.0
    depends_on:
      - frontend    
  worldserver:
    image: worldserver:1.0.0
    depends_on:
      - frontend    
